lan = [('cpp', 'C++'), ('text', 'Plains Text'), ('aspx-cs', 'aspx-cs'), ('aspx-vb', 'aspx-vb'),
       ('basemake', 'Makefile'), ('bash', 'Bash'), ('bat', 'Batchfile'), ('c', 'C'), ('cmake', 'CMake'),
       ('csharp', 'C#'), ('css', 'CSS'), ('css+django', 'CSS+Django/Jinja'), ('css+erb', 'CSS+Ruby'),
       ('css+genshitext', 'CSS+Genshi Text'), ('css+mako', 'CSS+Mako'), ('css+myghty', 'CSS+Myghty'),
       ('css+php', 'CSS+PHP'), ('css+smarty', 'CSS+Smarty'), ('cython', 'Cython'), ('d', 'D'), ('delphi', 'Delphi'),
       ('diff', 'Diff'), ('django', 'Django/Jinja'), ('erlang', 'Erlang'), ('fortran', 'Fortran'), ('go', 'Go'),
       ('haskell', 'Haskell'), ('html', 'HTML'), ('html+cheetah', 'HTML+Cheetah'), ('html+django', 'HTML+Django/Jinja'),
       ('html+evoque', 'HTML+Evoque'), ('html+genshi', 'HTML+Genshi'), ('html+mako', 'HTML+Mako'),
       ('html+myghty', 'HTML+Myghty'), ('html+php', 'HTML+PHP'), ('html+smarty', 'HTML+Smarty'),
       ('html+velocity', 'HTML+Velocity'), ('hx', 'haXe'), ('hybris', 'Hybris'), ('jade', 'Jade'), ('java', 'Java'),
       ('js', 'JavaScript'), ('js+cheetah', 'JavaScript+Cheetah'), ('js+django', 'JavaScript+Django/Jinja'),
       ('js+erb', 'JavaScript+Ruby'), ('js+genshitext', 'JavaScript+Genshi Text'), ('js+mako', 'JavaScript+Mako'),
       ('js+myghty', 'JavaScript+Myghty'), ('js+php', 'JavaScript+PHP'), ('js+smarty', 'JavaScript+Smarty'),
       ('jsp', 'Java Server Page'), ('lhs', 'Literate Haskell'), ('lighty', 'Lighttpd configuration file'),
       ('llvm', 'LLVM'), ('logtalk', 'Logtalk'), ('lua', 'Lua'), ('make', 'Makefile'), ('mako', 'Mako'),
       ('maql', 'MAQL'), ('mason', 'Mason'), ('matlab', 'Matlab'), ('matlabsession', 'Matlab session'),
       ('minid', 'MiniD'), ('modelica', 'Modelica'), ('modula2', 'Modula-2'), ('moocode', 'MOOCode'),
       ('mupad', 'MuPAD'), ('mxml', 'MXML'), ('myghty', 'Myghty'), ('mysql', 'MySQL'), ('nasm', 'NASM'),
       ('newspeak', 'Newspeak'), ('nginx', 'Nginx configuration file'), ('numpy', 'NumPy'), ('objdump', 'objdump'),
       ('objective-c', 'Objective-C'), ('objective-j', 'Objective-J'), ('ocaml', 'OCaml'), ('ooc', 'Ooc'),
       ('perl', 'Perl'), ('php', 'PHP'), ('postscript', 'PostScript'), ('pot', 'Gettext Catalog'), ('pov', 'POVRay'),
       ('prolog', 'Prolog'), ('properties', 'Properties'), ('py3tb', 'Python 3.0 Traceback'),
       ('pycon', 'Python console session'), ('pytb', 'Python Traceback'), ('python', 'Python'), ('python3', 'Python 3'),
       ('ragel', 'Ragel'), ('ragel-c', 'Ragel in C Host'), ('ragel-cpp', 'Ragel in CPP Host'),
       ('ragel-d', 'Ragel in D Host'), ('ragel-em', 'Embedded Ragel'), ('ragel-java', 'Ragel in Java Host'),
       ('ragel-objc', 'Ragel in Objective C Host'), ('ragel-ruby', 'Ragel in Ruby Host'), ('rb', 'Ruby'),
       ('rbcon', 'Ruby irb session'), ('rebol', 'REBOL'), ('redcode', 'Redcode'), ('rhtml', 'RHTML'),
       ('rst', 'reStructuredText'), ('sass', 'Sass'), ('scala', 'Scala'), ('scaml', 'Scaml'), ('scheme', 'Scheme'),
       ('scss', 'SCSS'), ('sql', 'SQL'), ('sqlite3', 'sqlite3con'), ('tex', 'TeX'), ('text', 'Text only'),
       ('vb.net', 'VB.net'), ('xml', 'XML'), ('xml+cheetah', 'XML+Cheetah'), ('xml+django', 'XML+Django/Jinja'),
       ('xml+erb', 'XML+Ruby'), ('xml+evoque', 'XML+Evoque'), ('xml+mako', 'XML+Mako'), ('xml+myghty', 'XML+Myghty'),
       ('xml+php', 'XML+PHP'), ('xml+smarty', 'XML+Smarty'), ('xml+velocity', 'XML+Velocity'), ('xquery', 'XQuery'),
       ('xslt', 'XSLT'), ('yaml', 'YAML')]
for l in lan:
    print(l[1])
